/*
 * CadastroEstadoCivil.java
 *
 * Created on May 27, 2008, 9:09 PM
 */
package quickphones;

import br.com.perettis.gets.dao.DAOConstants;
import br.com.perettis.gets.swing.FormSearch;
import br.com.perettis.gets.swing.NumericDocument;
import br.com.perettis.gets.swing.GetsDocument;
import br.com.perettis.gets.dao.DAOFactoryAbstract;
import br.com.perettis.gets.swing.FormSearchColumn;
import br.com.perettis.gets.text.BooleanFormat;
import quickphones.entity.Usuario;
import quickphones.model.QuickPhonesDAOFactory;
import quickphones.model.Seguranca;
import quickphones.model.UsuarioDAO;
import java.awt.event.KeyEvent;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import org.hibernate.Transaction;
import org.jdesktop.application.Action;

/**
 *
 * @author  Vinicius Peretti
 * 
 * 
 */
public class CadastroUsuario extends javax.swing.JFrame {

    Usuario usuario;
    UsuarioDAO UsuarioDAO;
    private QuickPhonesDAOFactory daoFactory;
    Transaction t;
    org.jdesktop.application.ResourceMap resourceMap;
    FormSearch<Long, Usuario, UsuarioDAO> pesquisa;

    /** Creates new form CadastroEstadoCivil */
    public CadastroUsuario(QuickPhonesDAOFactory daoFactory) {
        setDaoFactory(daoFactory);
        initComponents();
        ResetaForm();
        resourceMap = org.jdesktop.application.Application.getInstance(
                quickphones.QuickPhonesApp.class).getContext().getResourceMap(CadastroUsuario.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alerta = new javax.swing.JOptionPane();
        lCodigo = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbDesabilitado = new javax.swing.JCheckBox();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        txtId = new javax.swing.JFormattedTextField();
        txtApelido = new javax.swing.JFormattedTextField();
        lApelido = new javax.swing.JLabel();
        txtNome = new javax.swing.JFormattedTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        cbAdministrador = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JFormattedTextField();

        alerta.setName("alerta"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(quickphones.QuickPhonesApp.class).getContext().getResourceMap(CadastroUsuario.class);
        lCodigo.setText(resourceMap.getString("lCodigo.text")); // NOI18N
        lCodigo.setName("lCodigo"); // NOI18N

        lNome.setText(resourceMap.getString("lNome.text")); // NOI18N
        lNome.setName("lNome"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(quickphones.QuickPhonesApp.class).getContext().getActionMap(CadastroUsuario.class, this);
        btnNovo.setAction(actionMap.get("Novo")); // NOI18N
        btnNovo.setText(resourceMap.getString("btnNovo.text")); // NOI18N
        btnNovo.setName("btnNovo"); // NOI18N

        btnSalvar.setAction(actionMap.get("Salvar")); // NOI18N
        btnSalvar.setText(resourceMap.getString("btnSalvar.text")); // NOI18N
        btnSalvar.setName("btnSalvar"); // NOI18N

        btnCancelar.setAction(actionMap.get("Cancelar")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        cbDesabilitado.setText(resourceMap.getString("cbDesabilitado.text")); // NOI18N
        cbDesabilitado.setName("cbDesabilitado"); // NOI18N

        btnExcluir.setAction(actionMap.get("Excluir")); // NOI18N
        btnExcluir.setText(resourceMap.getString("btnExcluir.text")); // NOI18N
        btnExcluir.setName("btnExcluir"); // NOI18N

        btnPesquisar.setAction(actionMap.get("Pesquisar")); // NOI18N
        btnPesquisar.setText(resourceMap.getString("btnPesquisar.text")); // NOI18N
        btnPesquisar.setName("btnPesquisar"); // NOI18N

        txtId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId.setName("txtId"); // NOI18N
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        txtApelido.setName("txtApelido"); // NOI18N

        lApelido.setText(resourceMap.getString("lApelido.text")); // NOI18N
        lApelido.setName("lApelido"); // NOI18N

        txtNome.setText(resourceMap.getString("txtNome.text")); // NOI18N
        txtNome.setName("txtNome"); // NOI18N

        txtSenha.setText(resourceMap.getString("txtSenha.text")); // NOI18N
        txtSenha.setName("txtSenha"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        cbAdministrador.setText(resourceMap.getString("cbAdministrador.text")); // NOI18N
        cbAdministrador.setName("cbAdministrador"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        txtEmail.setText(resourceMap.getString("txtEmail.text")); // NOI18N
        txtEmail.setName("txtEmail"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lApelido)
                    .addComponent(jLabel1)
                    .addComponent(lCodigo)
                    .addComponent(lNome)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDesabilitado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir))
                            .addComponent(cbAdministrador))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnPesquisar)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lApelido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(cbAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDesabilitado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        NumericDocument gdId = new NumericDocument();
        gdId.setMaxLenght(6);
        txtId.setDocument(gdId);
        GetsDocument gdDescricao = new GetsDocument();
        gdDescricao.setMaxLenght(50);
        txtApelido.setDocument(gdDescricao);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
    if (!txtId.getText().equalsIgnoreCase("")) {
        Alterar();
    }
}//GEN-LAST:event_txtIdFocusLost

    @SuppressWarnings("static-access")
private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
}//GEN-LAST:event_txtIdKeyTyped

private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_F10) {
        Pesquisar();
    }
}//GEN-LAST:event_txtIdKeyPressed

	
	
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CadastroEstadoCivil().setVisible(true);
            }
        });
    }
    
    /**
     * Reinicia formulário
     */
  	public void ResetaForm() {
		txtId.setText("");
		txtApelido.setText("");
        txtSenha.setText("");
        txtNome.setText("");
        txtEmail.setText("");
        cbAdministrador.setSelected(false);
		cbDesabilitado.setSelected(false);
		txtId.setEnabled(true);
		txtId.requestFocus();
		btnSalvar.setEnabled(false);
		btnExcluir.setEnabled(false);
	}
    
    @Action
    /**
     * Abre tela de pesquisa
     */
    public void Pesquisar(){
        if (pesquisa == null) {
            pesquisa = new FormSearch();
            Set<FormSearchColumn> colunas = new LinkedHashSet<FormSearchColumn>();


            FormSearchColumn fscApelido = new FormSearchColumn();
            fscApelido.setProperty("apelido");
            fscApelido.setPropertyClass(String.class);
            fscApelido.setLabel("Apelido");
            fscApelido.setWidth(200);
            fscApelido.setAlign(SwingConstants.LEFT);
            fscApelido.setTypeSearch(DAOConstants.LIKE);
            colunas.add(fscApelido);

            FormSearchColumn fscNome = new FormSearchColumn();
            fscNome.setProperty("nome");
            fscNome.setPropertyClass(String.class);
            fscNome.setLabel("Nome");
            fscNome.setWidth(300);
            fscNome.setAlign(SwingConstants.LEFT);
            fscNome.setTypeSearch(DAOConstants.LIKE);
            colunas.add(fscNome);


            FormSearchColumn fscId = new FormSearchColumn();
            fscId.setProperty("id");
            fscId.setPropertyClass(Long.class);
            fscId.setLabel("ID");
            fscId.setWidth(100);
            fscId.setAlign(SwingConstants.RIGHT);
            fscId.setTypeSearch(DAOConstants.ABOVE_EQUAL);
            colunas.add(fscId);


            // Cria formatador da coluna desabilitado
            BooleanFormat desFormat = new BooleanFormat();
            desFormat.setTrueString("desabilitado");
            desFormat.setFalseString("habilitado");

            FormSearchColumn fscDesabilitado = new FormSearchColumn();
            fscDesabilitado.setProperty("desabilitado");
            fscDesabilitado.setPropertyClass(Boolean.class);
            fscDesabilitado.setLabel("Situação");
            fscDesabilitado.setWidth(10);
            fscDesabilitado.setAlign(SwingConstants.CENTER);
            fscDesabilitado.setTypeSearch(DAOConstants.EQUAL);
            fscDesabilitado.setFormatter(desFormat);
            colunas.add(fscDesabilitado);
            

            pesquisa.setIdProperty("id");
            pesquisa.setIdClass(Long.class);
            pesquisa.setColumns(colunas);
            pesquisa.setDefaultProperty("apelido");
            pesquisa.setEntityClass(Usuario.class);
            pesquisa.setDaoClass(UsuarioDAO.class);
            pesquisa.setDaoFactory((DAOFactoryAbstract) getDaoFactory());
            pesquisa.setTitle("Selecione o Usuário para Alteração.");
            pesquisa.makeForm();
            pesquisa.getRbAny().setSelected(true);
            //pesquisa.setKeySearch("teste");
            //pesquisa.doSearch();
        }
        
        pesquisa.openSearch();
        Usuario vem = pesquisa.getEntity();
        if (vem != null){
            txtId.setText(String.valueOf(vem.getId()));
            Alterar();
        }
    }

	@Action
    /**
     * Prepara formulário para novo cadastro
     */
	public void Novo() {
		ResetaForm();
		txtId.setEnabled(false);
		usuario = new Usuario();
		UsuarioDAO = daoFactory.getUsuarioDAO();
		btnSalvar.setEnabled(true);
	}

	@Action
    /**
     * Salva novo cadastro ou altera
     */
	public void Salvar() {

        // se id for nulo trata como inclusão
		if (usuario.getId() == null) {
            usuario = new Usuario();
			t = UsuarioDAO.getSession().beginTransaction();
			t.begin();
			try {
                //Verifica se já existe mesma descrição
				if (UsuarioDAO.buscaPorApelido(txtApelido.getText())
						!= null) {
					JOptionPane.showMessageDialog(
						this,
						resourceMap.getString("jaexiste.apelido", 
							String.valueOf(txtApelido.getText())));
					txtApelido.requestFocus();
					return;
				}

				// Preenche dado nos objetos
				usuario.setApelido(txtApelido.getText());
                //TODO usar metodo getPassword, preciso converter char to byte
                if (!txtSenha.getText().equalsIgnoreCase("")){
                    usuario.setSenha(Seguranca.CriptografaSenha(txtSenha.getText()));
                }
                usuario.setNome(txtNome.getText());
                usuario.setEmail(txtEmail.getText());
                usuario.setAdministrador(cbAdministrador.isSelected());
				usuario.setDesabilitado(cbDesabilitado.isSelected());
                
                // Grava 
				UsuarioDAO.makePersistent(usuario);
				t.commit();
                
                // Confirma
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.sucesso", 
						String.valueOf(usuario.getId())));
                // Reseta
                usuario = null;
                ResetaForm();
			} catch (Exception e) {
                // Se ocorre algum erro, mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.erro") +
					e.getLocalizedMessage());
				t.rollback();
			}


		// Se for alteração
		} else {
            try {
                // Verifica se existe outro com mesmos dados
                Usuario outro = UsuarioDAO.buscaPorApelido(
                        txtApelido.getText());
                if (outro != null) {
                    if (outro.getId() != usuario.getId()) {

                        JOptionPane.showMessageDialog(this,
                                resourceMap.getString("jaexiste.apelido",
                                String.valueOf(txtApelido.getText())));
                        txtApelido.requestFocus();
                        return;
                    }
                }

				// Preenche dados do form no objeto
				usuario.setApelido(txtApelido.getText());
                //TODO usar metodo getPassword, preciso converter char to byte
                if (!txtSenha.getText().equalsIgnoreCase("")){
                    usuario.setSenha(Seguranca.CriptografaSenha(txtSenha.getText()));
                }
                usuario.setNome(txtNome.getText());
                usuario.setEmail(txtEmail.getText());
                usuario.setAdministrador(cbAdministrador.isSelected());
				usuario.setDesabilitado(cbDesabilitado.isSelected());
                
                // Grava alterações
				UsuarioDAO.makePersistent(usuario);
				t.commit();
                
                // Mostra confirmação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.sucesso"));
                
                // Reinicia formulario
                usuario = null;
				ResetaForm();

			} catch (Exception e) {
                // Qualquer erro mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.erro") +
                        e.getLocalizedMessage());
				t.rollback();
			}
		}
	}

    /**
     * Abre cadastro no formulário para alteração
     */
	public void Alterar() {
        // Busca nova sessao
		UsuarioDAO = daoFactory.getUsuarioDAO();
		try {
            // Inicia transação
			t = UsuarioDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            usuario = UsuarioDAO.findById(
                    Long.valueOf(txtId.getText()), true);
            
            // Preenche dados no formulário
            txtApelido.setText(usuario.getApelido());
            txtNome.setText(usuario.getNome());
            txtEmail.setText(usuario.getEmail());
            cbAdministrador.setSelected(usuario.isAdministrador());
            cbDesabilitado.setSelected(usuario.isDesabilitado());
            
            // Ativa controles disponíveis
			btnSalvar.setEnabled(true);
			btnExcluir.setEnabled(true);

		} catch (Exception e) {
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("altera.errobusca", txtId.getText()));
			txtId.setEnabled(true);
			btnSalvar.setEnabled(false);
			btnExcluir.setEnabled(false);
			txtId.requestFocus();
		}
	}

	@Action
    /**
     * Limpa formulário, cancelando edição atual
     */
	public void Cancelar() {
		usuario = null;
		ResetaForm();
	}
	
	@Action
    /**
     * Exclui objeto atual
     */
	public void Excluir() {
		// Solicita confirmação
        int opcao = JOptionPane.showConfirmDialog(this,
                resourceMap.getString("exclui.confirmacao"),
                resourceMap.getString("exclui.confirmacao.titulo"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        switch (opcao) {
			case 0: // Resposta sim
				try {
                    // Remove da persistencia
					UsuarioDAO.makeTransient(usuario);
					t.commit();
                    // Confirma
					JOptionPane.showMessageDialog(this,
						resourceMap.getString("exclui.ok"));
                    // Limpa form
					usuario = null;
					ResetaForm();

				} catch (Exception e) {
                    // Dando erro diz que não é possivel
					JOptionPane.showMessageDialog(this,
						resourceMap.getString(
						"exclui.naopode"));
				}
				break;
			case 1: // Resposta não
				break;
		}

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alerta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox cbAdministrador;
    private javax.swing.JCheckBox cbDesabilitado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lApelido;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lNome;
    private javax.swing.JFormattedTextField txtApelido;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JFormattedTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

	public QuickPhonesDAOFactory getDaoFactory() {
		return daoFactory;
	}

	public void setDaoFactory(QuickPhonesDAOFactory daoFactory) {
		this.daoFactory = daoFactory;
	}

}
