/*
 * CadastroEstadoCivil.java
 *
 * Created on May 27, 2008, 9:09 PM
 */
package quickphones;

import br.com.perettis.gets.dao.DAOConstants;
import br.com.perettis.gets.swing.FormSearch;
import br.com.perettis.gets.swing.NumericDocument;
import br.com.perettis.gets.swing.GetsDocument;
import br.com.perettis.gets.dao.DAOFactoryAbstract;
import br.com.perettis.gets.swing.FormSearchColumn;
import br.com.perettis.gets.text.BooleanFormat;
import quickphones.model.QuickPhonesDAOFactory;
import quickphones.model.Seguranca;
import java.awt.event.KeyEvent;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import org.hibernate.Transaction;
import org.jdesktop.application.Action;
import quickphones.entity.Contato;
import quickphones.model.ContatoDAO;

/**
 *
 * @author  Vinicius Peretti
 * 
 * 
 */
public class CadastroContato extends javax.swing.JFrame {

    Contato contato;
    ContatoDAO contatoDAO;
    private QuickPhonesDAOFactory daoFactory;
    Transaction t;
    org.jdesktop.application.ResourceMap resourceMap;
    FormSearch<Long, Contato, ContatoDAO> pesquisa;

    /** Creates new form CadastroEstadoCivil */
    public CadastroContato(QuickPhonesDAOFactory daoFactory) {
        setDaoFactory(daoFactory);
        initComponents();
        ResetaForm();
        resourceMap = org.jdesktop.application.Application.getInstance(
                quickphones.QuickPhonesApp.class).getContext().getResourceMap(CadastroContato.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alerta = new javax.swing.JOptionPane();
        lCodigo = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        txtId = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        lNome1 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JFormattedTextField();
        lNome2 = new javax.swing.JLabel();
        txtContato = new javax.swing.JFormattedTextField();
        lNome3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JEditorPane();
        jLabel3 = new javax.swing.JLabel();

        alerta.setName("alerta"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(quickphones.QuickPhonesApp.class).getContext().getResourceMap(CadastroContato.class);
        lCodigo.setText(resourceMap.getString("lCodigo.text")); // NOI18N
        lCodigo.setName("lCodigo"); // NOI18N

        lNome.setText(resourceMap.getString("lNome.text")); // NOI18N
        lNome.setName("lNome"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(quickphones.QuickPhonesApp.class).getContext().getActionMap(CadastroContato.class, this);
        btnNovo.setAction(actionMap.get("Novo")); // NOI18N
        btnNovo.setText(resourceMap.getString("btnNovo.text")); // NOI18N
        btnNovo.setName("btnNovo"); // NOI18N

        btnSalvar.setAction(actionMap.get("Salvar")); // NOI18N
        btnSalvar.setText(resourceMap.getString("btnSalvar.text")); // NOI18N
        btnSalvar.setName("btnSalvar"); // NOI18N

        btnCancelar.setAction(actionMap.get("Cancelar")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        btnExcluir.setAction(actionMap.get("Excluir")); // NOI18N
        btnExcluir.setText(resourceMap.getString("btnExcluir.text")); // NOI18N
        btnExcluir.setName("btnExcluir"); // NOI18N

        btnPesquisar.setAction(actionMap.get("Pesquisar")); // NOI18N
        btnPesquisar.setText(resourceMap.getString("btnPesquisar.text")); // NOI18N
        btnPesquisar.setName("btnPesquisar"); // NOI18N

        txtId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId.setName("txtId"); // NOI18N
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        txtNome.setText(resourceMap.getString("txtNome.text")); // NOI18N
        txtNome.setName("txtNome"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        txtEmail.setText(resourceMap.getString("txtEmail.text")); // NOI18N
        txtEmail.setName("txtEmail"); // NOI18N

        txtTelefone.setName("txtTelefone"); // NOI18N

        lNome1.setText(resourceMap.getString("lNome1.text")); // NOI18N
        lNome1.setName("lNome1"); // NOI18N

        txtEndereco.setName("txtEndereco"); // NOI18N

        lNome2.setText(resourceMap.getString("lNome2.text")); // NOI18N
        lNome2.setName("lNome2"); // NOI18N

        txtContato.setName("txtContato"); // NOI18N

        lNome3.setText(resourceMap.getString("lNome3.text")); // NOI18N
        lNome3.setName("lNome3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtObs.setName("txtObs"); // NOI18N
        jScrollPane1.setViewportView(txtObs);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(lNome)
                            .addComponent(lNome2)
                            .addComponent(lNome1)
                            .addComponent(lCodigo)
                            .addComponent(lNome3)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar))
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(txtContato, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnPesquisar)
                    .addComponent(lCodigo)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNome))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNome1))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNome2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNome3)
                    .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluir)
                            .addComponent(btnCancelar)
                            .addComponent(btnSalvar))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );

        NumericDocument gdId = new NumericDocument();
        gdId.setMaxLenght(6);
        txtId.setDocument(gdId);
        new GetsDocument().setMaxLenght(255, txtNome);
        new GetsDocument().setMaxLenght(255, txtEmail);
        new GetsDocument().setMaxLenght(255, txtTelefone);
        new GetsDocument().setMaxLenght(255, txtEndereco);
        new GetsDocument().setMaxLenght(255, txtContato);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
    if (!txtId.getText().equalsIgnoreCase("")) {
        Alterar();
    }
}//GEN-LAST:event_txtIdFocusLost

    @SuppressWarnings("static-access")
private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
}//GEN-LAST:event_txtIdKeyTyped

private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_F10) {
        Pesquisar();
    }
}//GEN-LAST:event_txtIdKeyPressed

	
	
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CadastroEstadoCivil().setVisible(true);
            }
        });
    }
    
    /**
     * Reinicia formulário
     */
  	public void ResetaForm() {
		txtId.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
        txtContato.setText("");
        txtEmail.setText("");
        txtObs.setText("");
		txtId.setEnabled(true);
		txtId.requestFocus();
		btnSalvar.setEnabled(false);
		btnExcluir.setEnabled(false);
	}
    
    @Action
    /**
     * Abre tela de pesquisa
     */
    public void Pesquisar(){
        if (pesquisa == null) {
            pesquisa = new FormSearch();
            Set<FormSearchColumn> colunas = new LinkedHashSet<FormSearchColumn>();



            FormSearchColumn fscNome = new FormSearchColumn();
            fscNome.setProperty("nome");
            fscNome.setPropertyClass(String.class);
            fscNome.setLabel("Nome");
            fscNome.setWidth(300);
            fscNome.setAlign(SwingConstants.LEFT);
            fscNome.setTypeSearch(DAOConstants.LIKE);
            colunas.add(fscNome);

            FormSearchColumn fscTelefone = new FormSearchColumn();
            fscTelefone.setProperty("telefone");
            fscTelefone.setPropertyClass(String.class);
            fscTelefone.setLabel("Telefone");
            fscTelefone.setWidth(200);
            fscTelefone.setAlign(SwingConstants.LEFT);
            fscTelefone.setTypeSearch(DAOConstants.LIKE);
            colunas.add(fscTelefone);

            FormSearchColumn fscEndereco = new FormSearchColumn();
            fscEndereco.setProperty("endereco");
            fscEndereco.setPropertyClass(String.class);
            fscEndereco.setLabel("Endereço");
            fscEndereco.setWidth(200);
            fscEndereco.setAlign(SwingConstants.LEFT);
            fscEndereco.setTypeSearch(DAOConstants.LIKE);
            colunas.add(fscEndereco);
            
            FormSearchColumn fscContato = new FormSearchColumn();
            fscContato.setProperty("contato");
            fscContato.setPropertyClass(String.class);
            fscContato.setLabel("Contato");
            fscContato.setWidth(200);
            fscContato.setAlign(SwingConstants.LEFT);
            fscContato.setTypeSearch(DAOConstants.LIKE);
            colunas.add(fscContato);

            

            FormSearchColumn fscId = new FormSearchColumn();
            fscId.setProperty("id");
            fscId.setPropertyClass(Long.class);
            fscId.setLabel("ID");
            fscId.setWidth(100);
            fscId.setAlign(SwingConstants.RIGHT);
            fscId.setTypeSearch(DAOConstants.ABOVE_EQUAL);
            colunas.add(fscId);

            pesquisa.setIdProperty("id");
            pesquisa.setIdClass(Long.class);
            pesquisa.setColumns(colunas);
            pesquisa.setDefaultProperty("nome");
            pesquisa.setEntityClass(Contato.class);
            pesquisa.setDaoClass(ContatoDAO.class);
            pesquisa.setDaoFactory((DAOFactoryAbstract) getDaoFactory());
            pesquisa.setTitle("Pesquisa de contatos.");
            pesquisa.makeForm();
            pesquisa.getRbAny().setSelected(true);
            //pesquisa.setKeySearch("teste");
            //pesquisa.doSearch();
        }
        
        pesquisa.openSearch();
        Contato vem = pesquisa.getEntity();
        if (vem != null){
            txtId.setText(String.valueOf(vem.getId()));
            Alterar();
        }
    }

	@Action
    /**
     * Prepara formulário para novo cadastro
     */
	public void Novo() {
		ResetaForm();
		txtId.setEnabled(false);
		contato = new Contato();
		contatoDAO = daoFactory.getContatoDAO();
		btnSalvar.setEnabled(true);
	}

	@Action
    /**
     * Salva novo cadastro ou altera
     */
	public void Salvar() {

        // se id for nulo trata como inclusão
		if (contato.getId() == null) {
            contato = new Contato();
			t = contatoDAO.getSession().beginTransaction();
			t.begin();
			try {
                //Verifica se já existe mesma descrição
                /*
				if (contatoDAO.buscaPorApelido(txtApelido.getText())
						!= null) {
					JOptionPane.showMessageDialog(
						this,
						resourceMap.getString("jaexiste.apelido", 
							String.valueOf(txtApelido.getText())));
					txtApelido.requestFocus();
					return;
				}
                 */

				// Preenche dado nos objetos
                contato.setNome(txtNome.getText());
                contato.setTelefone(txtTelefone.getText());
                contato.setEndereco(txtEndereco.getText());
                contato.setContato(txtContato.getText());
                contato.setEmail(txtEmail.getText());
                contato.setObs(txtObs.getText());
                
                // Grava 
				contatoDAO.makePersistent(contato);
				t.commit();
                
                // Confirma
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.sucesso", 
						String.valueOf(contato.getId())));
                // Reseta
                contato = null;
                ResetaForm();
			} catch (Exception e) {
                // Se ocorre algum erro, mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this,
					resourceMap.getString("cadastro.erro") +
					e.getLocalizedMessage());
				t.rollback();
			}


		// Se for alteração
		} else {
            try {

				// Preenche dados do form no objeto
                contato.setNome(txtNome.getText());
                contato.setTelefone(txtTelefone.getText());
                contato.setEndereco(txtEndereco.getText());
                contato.setContato(txtContato.getText());
                contato.setEmail(txtEmail.getText());
                contato.setObs(txtObs.getText());
                
                // Grava alterações
				contatoDAO.makePersistent(contato);
				t.commit();
                
                // Mostra confirmação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.sucesso"));
                
                // Reinicia formulario
                contato = null;
				ResetaForm();

			} catch (Exception e) {
                // Qualquer erro mostra mensagem e desfaz transação
				JOptionPane.showMessageDialog(this, 
                        resourceMap.getString("altera.erro") +
                        e.getLocalizedMessage());
				t.rollback();
			}
		}
	}

    /**
     * Abre cadastro no formulário para alteração
     */
	public void Alterar() {
        // Busca nova sessao
		contatoDAO = daoFactory.getContatoDAO();
		try {
            // Inicia transação
			t = contatoDAO.getSession().beginTransaction();
            
            // Busca objeto pelo id informado
            contato = contatoDAO.findById(
                    Long.valueOf(txtId.getText()), true);
            
            // Preenche dados no formulário
            txtNome.setText(contato.getNome());
            txtTelefone.setText(contato.getTelefone());
            txtEndereco.setText(contato.getEndereco());
            txtContato.setText(contato.getContato());
            txtEmail.setText(contato.getEmail());
            txtObs.setText(contato.getObs());
            
            // Ativa controles disponíveis
			btnSalvar.setEnabled(true);
			btnExcluir.setEnabled(true);

		} catch (Exception e) {
            // Se não acha, nostra mensagem
			JOptionPane.showMessageDialog(this, 
                    resourceMap.getString("altera.errobusca", txtId.getText()));
			txtId.setEnabled(true);
			btnSalvar.setEnabled(false);
			btnExcluir.setEnabled(false);
			txtId.requestFocus();
		}
	}

	@Action
    /**
     * Limpa formulário, cancelando edição atual
     */
	public void Cancelar() {
		contato = null;
		ResetaForm();
	}
	
	@Action
    /**
     * Exclui objeto atual
     */
	public void Excluir() {
		// Solicita confirmação
        int opcao = JOptionPane.showConfirmDialog(this,
                resourceMap.getString("exclui.confirmacao"),
                resourceMap.getString("exclui.confirmacao.titulo"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        switch (opcao) {
			case 0: // Resposta sim
				try {
                    // Remove da persistencia
					contatoDAO.makeTransient(contato);
					t.commit();
                    // Confirma
					JOptionPane.showMessageDialog(this,
						resourceMap.getString("exclui.ok"));
                    // Limpa form
					contato = null;
					ResetaForm();

				} catch (Exception e) {
                    // Dando erro diz que não é possivel
					JOptionPane.showMessageDialog(this,
						resourceMap.getString(
						"exclui.naopode"));
				}
				break;
			case 1: // Resposta não
				break;
		}

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alerta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lNome1;
    private javax.swing.JLabel lNome2;
    private javax.swing.JLabel lNome3;
    private javax.swing.JFormattedTextField txtContato;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JFormattedTextField txtEndereco;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JFormattedTextField txtNome;
    private javax.swing.JEditorPane txtObs;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

	public QuickPhonesDAOFactory getDaoFactory() {
		return daoFactory;
	}

	public void setDaoFactory(QuickPhonesDAOFactory daoFactory) {
		this.daoFactory = daoFactory;
	}

}
