jLabel1.text=Nome de Usu\u00E1rio:
jLabel2.text=Senha:
jButton1.text=Entrar
jButton2.text=Cancelar
txtPassword.text=
txtUsername.text=
jLabel3.text=Autentica\u00E7\u00E3o QuickPhones
#NOI18N
jLabel3.font=DejaVu LGC Sans-Plain-18
