# Application global resources

Application.name = QuickPhones
Application.title = Quick Phones
Application.version = 1.0
Application.vendor = Peretti Assessoria e Sistemas Ltda.
Application.homepage = http://www.perettis.com.br/
Application.description = Simples aplica\u00E7\u00E3o de consulta de contatos.
Application.vendorId = Peretti
Application.id = QuickPhones
Application.lookAndFeel = system
